### ISSUE TITLE
Error in Readme and Official Docs

### ISSUE THREAD

**Issue by akhi4u** [splitio/go-client#105]
Official docs and Readme have an error in the sample snippet.
This `err = client.BlockUntilReady(10)` 
should be 
`err = factory.BlockUntilReady(10)`.

**Comment by mredolatti** [comment]
Hi @akhi4u,
Thanks for reaching out. Are you having trouble calling this method from the Client?
As you can see in the link below it's implemented by the client, which in turn forwards the call to the factory:

https://github.com/splitio/go-client/blob/master/splitio/client/client.go#L384

Please let us know if this is an issue for you or it's not working as expected.

Thanks,
Martin.

**Comment by akhi4u** [comment]
So if I use the example as it is, I get `undefined: client.BlockUntilReady`. That's why I changed it to `factory.BlockUntilReady(10)`.

**Comment by mredolatti** [comment]
Hi @akhi4u ,

There is indeed an error in the documentation, since we forgot to specify that you need to instantiate the client first, by doing 

`splitClient := factory.Client()`

and then you can call `splitClient.BlockUntilReady(...)`

the symbol `client` ends up referring to the module containing the implementation classes, and not the client instance itself.

We will update the docs to reflect this.
Thank you very much for letting us know, and please don't hesitate to reach out again if you see anything else odd, or need assistance.

Regards,
Martin

**Comment by akhi4u** [comment]
Thank you so much for all the help.

**Comment by mredolatti** [comment]
@akhi4u ,

We have updated our docs as per your suggestion.
Thank you very much for your help, and our apologizes for any inconveniences caused.

I'm gonna close this, but feel free to reopen if necessary.

Regards,
Martin.
