### ISSUE TITLE
Return error instead of logging it on the Treatment method.

### ISSUE THREAD

**Issue by luklss** [splitio/go-client#145]
In my opinion the `Treatment` method signature has a considerable design flaw. Currently if there is an error on the SDK side, the SDK will log something like `ERROR - 2021/11/25 11:48:29 RegexMatcher:  Attribute "country" required but not present in provided attribute map  instead of returning an error` instead of returning an error. That has two problems. The first and biggest is that I, as a user of the SDK, have no chance of catching this error and act accordingly. Secondly, it is quite annoying that the SDK logs stuff without me wanting to. Again, if I wanted to log the error, I could catch it and log it myself.

**Comment by NicoZelaya** [comment]
Hi @luklss ! 

I apologize for the inconveniences and the noisy logs, but those are meant to catch your attention. Just in a way a bit less disruptive than an exception. 

Now our SDKs are designed to avoid exceptions in order to avoid affecting the execution of your app, since that error shouldn't be enough to justify an exception (as in the worst case scenario you get `control` treatment). 
For example, if we were to throw exceptions and someone adds a new matching rule with a new attribute before the modified code adding it is running in production you would start getting exceptions. While today this won't affect functionality, you'll just need to be good with that particular attribute not matching until provided.

While this approach might not be preferred by everyone, it is still the safest option we could find considering all scenarios.

Best,
Nico.

**Comment by luklss** [comment]
Hey @NicoZelaya ,

I understand your rationale, but would prefer getting a specific error type I could then catch. For instance `ErrorRequiredAttributeNotProvided`. Then I could still handle this as I would handle control, but send an alert in our systems to notify that someone is probably making the wrong call to the API. Just having a log like this does not allow me to do that in a clean way (without having to regex for specific logs + rely on your logs not changing etc).

Regarding safety, if your API return an error, then that error should be handled. I personally do not think that this is less safe.

Anyways, those are my fifty cents on the matter. Thanks for your attention 🙂 .

Best,
Lucas

**Comment by agustinona** [comment]
Hi @luklss,

Thank you for your feedback! I've submitted your suggestion as a feature request for our product team to evaluate.

Best,
Agus
