### ISSUE TITLE
Go modules support 

### ISSUE THREAD

**Issue by bvwells** [splitio/go-client#90]
Hi,

It would be great if github.com/splitio/go-client supported go modules. See 
https://github.com/golang/go/wiki/Modules

As the library is already v2+ the change would be a little bit more involved. See:
https://github.com/golang/go/wiki/Modules#strategies-for-authors-of-pre-existing-v2-packages

It would also require changes to the way you git tag releases so that they are of the form v(major).(minor).(patch) (e.g. v5.1.0).

Thanks,
Ben

**Comment by mredolatti** [comment]
Hi @bvwells ! Thanks for raising this concern. At the moment of writing the SDK `dep` was the "official experiment", so we ended up using such tool to set up packaging. We will evaluate your proposal with the rest of the team and come back to you. But since the go community seems to be moving forward in this direction, we'll most probably start supporting modules in future releases.

Once again, thank you very much for reaching out with this suggestion!
Martin.

**Comment by bvwells** [comment]
@mredolatti thanks for the reply and for considering this. Fully understand that it's still early days for go modules and the change will effect your development practices.

**Comment by allanglen** [comment]
Another vote for updating to go modules.

Currently if you `go get` this package it uses the master branch of `github.com/splitio/go-toolkit` which isn't compatible with the master branch of this repo. 

```
# github.com/splitio/go-client/splitio/client
/go/pkg/mod/github.com/splitio/go-client@v0.0.0-20200507202154-752c678fb7d9/splitio/client/factory.go:250:22: not enough arguments in call to f.tasks.splits.Stop
        have ()
        want (bool)
```

Version 1.1.1 of the toolkit package is pinned via Dep (Gopkg.toml) but that isn't picked up by go modules.

**Comment by vvalima** [comment]
Thanks for the go-client. Another vote for modules coming from here.

Workaround for projects using solely modules was adding the following replace to `go.mod`:

```
replace (
	github.com/splitio/go-toolkit => github.com/splitio/go-toolkit v0.0.0-20200212181556-00febd183f5e
)
```

**Comment by mredolatti** [comment]
Hello guys, we've been working on initial support for go modules in all our repos and would love your feedback.
in case you want to try it, you should import you can use the `v6` package suffix and reference the tag `v6.0.0-rc2` on github. go-toolkit should be handled automatically since it's a direct dependency of go-client.

Thank you very much for the patience.

**Comment by bvwells** [comment]
Looks to be working as expected! Thanks for the update.

**Comment by bvwells** [comment]
Thanks for supporting go modules!

**Comment by bvwells** [comment]
Thanks for closing the issue @NicoZelaya. From what I can see the modules support is still not part of the master branch and is on the branch feature/module-support as this branch has the v6.0.0 git tag. Seems a non obvious branching strategy for modules and it is not obvious to consumers that the package actually supports modules. Is the the final branch strategy for the package?

**Comment by mredolatti** [comment]
HI @bvwells, we apologise if this is confusing. 
Since migrating to modules implies a breaking change with regards to dependencies and import paths, and we didn't want to break all of our customers code who may still be using dep, we decided to release v6 with modules with specific instruction in our docs (https://help.split.io/hc/en-us/articles/360020093652-Go-SDK#1-installing-the-sdk-into-your-go-environment) but not make it the default branch yet. 

Since version 7.0, modules support will be in the default branch, and `dep` will no longer be supported.

**Comment by bvwells** [comment]
Thanks for the clarification @mredolatti! I wonder whether it's worth adding a link in the README to these docs...
